apiVersion: apps/v1
kind: Deployment
metadata:
  name: burgerback-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: burgerback
  template:
    metadata:
      labels:
        app: burgerback
        version: v0.1
    spec:
      containers:
      - name: burgerback
        image: burger-back:0.1
        resources: 
          requests:
            memory: "100Mi"
          limits:
            memory: "200Mi"
        ports:
        - containerPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: burgerfront-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: burgerfront
  template: 
    metadata:
      labels:
        app: burgerfront
        version: v0.7
    spec:
      containers:
      - name: burgerfront
        image: burger-front:0.8
        ports:
        - containerPort: 3000
        env:
        - name: BACKEND
          value: http://burgerback:5000
---
apiVersion: v1
kind: Service
metadata:
  name: burgerback
spec:
  selector:
    app: burgerback
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: burgerfront
spec:
  selector:
    app: burgerfront
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: burgerfront
  labels:
    name: burgerfront
  annotations:
spec:
  ingressClassName: ngrok
  rules:
  - host: burger-places.ngrok.app
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: burgerfront
            port:
              number: 3000